--<ScriptOptions statementTerminator=";"/>


DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
		FIRSTNAME VARCHAR(20) NOT NULL,
		LASTNAME VARCHAR(30),
		EMAIL VARCHAR(50) NOT NULL,
		CONTACT BIGINT,
		DOB VARCHAR(30),
		GENDER CHAR(6),
		USERNAME BIGINT PRIMARY KEY NOT NULL,
		PASSWORD VARCHAR(30) NOT NULL
	);

	ALTER TABLE EMPLOYEE ALTER PASSWORD SET DATA TYPE VARCHAR(250);
	
	select * from EMPLOYEE;
	
	
	CREATE TABLE ALBUMS (
		ALBUM_ID BIGINT PRIMARY KEY NOT NULL,
		ALBUM_NAME VARCHAR(50) NOT NULL,
		ALBUM_DESCRIPTION VARCHAR(250),
		ALBUM_RESOURCES_PATH VARCHAR(1000),
		ALBUM_THUMBNAIL VARCHAR(200)
	);

CREATE TABLE FUNDCYCLE (
	FUNDID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
	STARTDATE DATE NOT NULL,
	ENDDATE DATE,
	ISINPROGRESS boolean default true,
	SHAREPERPERSON double NOT NULL
);
